In [1]:
import numpy as np

In [ ]:
!gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK

Downloading...
From: https://drive.google.com/uc?id=1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK
To: /content/survey.txt
100% 2.55k/2.55k [00:00<00:00, 6.46MB/s]


In [ ]:
s=np.loadtxt('survey.txt',dtype='int')
s.dtype,s.size,len(s),s.shape,s.ndim

(dtype('int64'), 1167, 1167, (1167,), 1)

In [ ]:
p=sum(s>=9)
d=sum(s<=6)
print(((p-d)/len(s))*100)
p,d

23.736075407026565


(np.int64(609), np.int64(332))

In [ ]:
a=np.random.randint(1,99,(4,5))
a

array([[42,  8, 71, 29, 25],
       [77, 57, 33, 62, 68],
       [39, 58, 21, 49, 29],
       [71,  5, 32, 85, 22]])

In [ ]:
np.zeros_like(a)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
x=np.random.randint(1,9,(4,3))
x,x.ndim,x.shape

(array([[7, 4, 6],
        [5, 2, 7],
        [8, 1, 3],
        [7, 3, 4]]),
 2,
 (4, 3))

In [ ]:
y=np.array([1,1,1])
y,y.ndim,y.shape

(array([1, 1, 1]), 1, (3,))

In [ ]:
x+y

array([[8, 5, 7],
       [6, 3, 8],
       [9, 2, 4],
       [8, 4, 5]])

In [ ]:
z=np.array([[1],[1],[1],[1]])
z,z.ndim,z.shape

(array([[1],
        [1],
        [1],
        [1]]),
 2,
 (4, 1))

In [ ]:
z1=np.array([1,1,1,1])
z1,z1.ndim,z1.shape

(array([1, 1, 1, 1]), 1, (4,))

In [ ]:
z+z1

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [ ]:
x

array([[7, 4, 6],
       [5, 2, 7],
       [8, 1, 3],
       [7, 3, 4]])

In [ ]:
y

array([1, 1, 1])

In [ ]:
np.tile(y,(3,3))

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
!gdown 1vk1Pu0djiYcrdc85yUXZ_Rqq2oZNcohd

Downloading...
From: https://drive.google.com/uc?id=1vk1Pu0djiYcrdc85yUXZ_Rqq2oZNcohd
To: /content/fit.txt
100% 3.43k/3.43k [00:00<00:00, 8.51MB/s]


In [ ]:
f=np.loadtxt('fit.txt',dtype='str')

/tmp/ipython-input-162-2112505294.py:1: UserWarning: Input line 1 contained no data and will not be counted towards `max_rows=50000`.  This differs from the behaviour in NumPy <=1.22 which counted lines rather than rows.  If desired, the previous behaviour can be achieved by using `itertools.islice`.
Please see the 1.23 release notes for an example on how to do this.  If you wish to ignore this warning, use `warnings.filterwarnings`.  This warning is expected to be removed in the future and is given only once per `loadtxt` call.
  f=np.loadtxt('fit.txt',dtype='str')


In [ ]:
np.loadtxt?

In [ ]:
f[0][:]

array(['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
      dtype='<U10')

In [ ]:
f.ndim,f.shape

(2, (96, 6))

In [ ]:
avg_step=np.mean(f[f[:,-1]=="Active"][:,1].astype('int'))

In [ ]:
np.round(avg_step,2)

np.float64(3226.57)

In [ ]:
actv=(f[:,-1]=="Active")

In [ ]:
f_actv=f[actv]

In [ ]:
np.mean(f_actv[:,1].astype('int'))

np.float64(3226.5714285714284)

In [ ]:
np.round?

In [ ]:
sum((f[:,1].astype('int')>5000) & (f[:,3].astype('int')>150))

np.int64(17)

In [ ]:
(f[:,1].astype('int')>5000) & (f[:,3].astype('int')>150)

array([ True,  True, False,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False,  True, False,  True,  True, False, False, False, False,
        True, False, False, False, False, False,  True, False, False,
       False, False, False, False,  True, False,  True, False, False,
       False, False, False,  True, False, False, False, False, False,
        True, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [ ]:
100*sum(f[:,2]=="Sad")/len(f[:,2])

np.float64(30.208333333333332)

In [ ]:
sum(f[:,2]=="Sad")

np.int64(29)

In [ ]:
np.max(f[f[:,-2].astype('int')<6][:,1].astype('int'))

np.int64(7422)

In [ ]:
f[f[:,-1]=="Inactive"][:,3].astype('int').mean()

np.float64(86.48148148148148)

In [ ]:
happy_sc=f[f[:,2]=="Happy"][:,1].astype('int')
sad_sc=f[f[:,2]=="Sad"][:,1].astype('int')
neutral_sc=f[f[:,2]=="Neutral"][:,1].astype('int')

In [ ]:
sum(sad_sc)/len(sad_sc),sum(happy_sc)/len(happy_sc),sum(neutral_sc)/len(neutral_sc)

(np.float64(2103.0689655172414),
 np.float64(3392.725),
 np.float64(3153.777777777778))

In [ ]:
np.mean(happy_sc),np.mean(sad_sc),np.mean(neutral_sc)

(np.float64(3392.725),
 np.float64(2103.0689655172414),
 np.float64(3153.777777777778))

In [ ]:
100*sum(f[:,2]=="Sad")/len(f[:,2])

np.float64(30.208333333333332)

In [ ]:
max(f[f[:,-2].astype('int')<6][:,1].astype('int'))

np.int64(7422)

In [ ]:
cal=f[f[:,-1]=="Inactive"][:,-3].astype('int')

In [ ]:
slp=f[f[:,-1]=="Inactive"][:,-2].astype('int')

In [ ]:
np.mean(cal/slp)

np.float64(18.62282480893592)

In [ ]:
np.corrcoef(f[:,1].astype('int'),f[:,3].astype('int'))[0,1]

np.float64(0.9892596952985985)

In [ ]:
np.sum((f[:,2]=="Sad") & (f[:,-2].astype('int')<np.median(f[:,-2].astype('int'))))

np.int64(10)

In [ ]:
np.std(f[f[:,2]=="Happy"][:,1].astype('int'))

np.float64(2088.4016254961593)

In [ ]:
value,counts=np.unique(f[:,-2].astype('int'),return_counts=True)

In [ ]:
value,counts

(array([2, 3, 4, 5, 6, 7, 8, 9]), array([ 3,  9, 14, 37, 16,  6, 10,  1]))

In [ ]:
value[np.argmax(counts)]

np.int64(5)

In [ ]:
mood=f[:,2]
step_count=f[:,1].astype('int')
calories_burned=f[:,3].astype('int')
hours_of_sleep=f[:,4].astype('int')
activity=f[:,-1]

In [ ]:
np.unique(mood)

array(['Happy', 'Neutral', 'Sad'], dtype='<U10')

In [ ]:
np.unique(mood)[np.argmin([np.mean(calories_burned[(mood==m)&(step_count>4000)&(hours_of_sleep>np.median(hours_of_sleep))]) for m in np.unique(mood)])]

np.str_('Neutral')

In [ ]:
days=(calories_burned[activity=="Inactive"]<np.mean(calories_burned))

In [ ]:
len(activity=="Inactive")

96

In [ ]:
len(calories_burned[activity=="Inactive"]),len(calories_burned)

(54, 96)

In [ ]:
calories_burned <  np.mean(calories_burned)

array([False, False,  True, False, False, False, False,  True,  True,
        True, False, False, False, False,  True,  True,  True, False,
       False, False, False,  True,  True,  True,  True, False, False,
       False,  True,  True,  True, False, False, False, False, False,
       False,  True, False, False, False, False,  True,  True,  True,
       False, False, False, False, False,  True,  True,  True,  True,
       False, False,  True,  True, False,  True, False,  True, False,
        True,  True,  True,  True, False, False, False,  True,  True,
        True, False,  True, False, False, False,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [ ]:
len(activity),len(activity=="Inactive"),len(calories_burned <  np.mean(calories_burned))

(96, 96, 96)

In [ ]:
days=((activity=="Inactive") & (calories_burned <  np.mean(calories_burned)))

In [ ]:
d=days.astype('int')

In [ ]:
# Find streak starts and ends
# Pad with 0s at both ends to catch edge streaks
padded=np.concatenate(([0], d, [0]))
diff = np.diff(padded)
starts = np.where(diff == 1)[0]
ends = np.where(diff == -1)[0]

# Compute lengths of True streaks
lengths = ends - starts

# Get the longest streak
longest_streak = lengths.max() if lengths.size > 0 else 0

In [ ]:
longest_streak

np.int64(8)

In [ ]:
diff=np.diff(np.concatenate(([0], d, [0])))
diff,np.concatenate(([0], d, [0]))

(array([ 0,  0,  1, -1,  0,  0,  0,  1,  0,  0, -1,  0,  0,  0,  1,  0,  0,
        -1,  0,  0,  0,  1,  0,  0,  0, -1,  0,  0,  1,  0, -1,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,
        -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1, -1,  0,  1, -1,
         0,  0,  0,  0,  1, -1,  0,  0,  0,  0,  1,  0,  0, -1,  0,  0,  0,
         1,  0,  0,  0,  0,  0,  0,  0, -1,  1, -1,  0]),
 array([0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
        1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
        1, 1, 1, 1, 1, 1, 0, 1, 0, 0]))

In [ ]:
np.where(diff==1)[0],np.where(diff==-1)[0]

(array([ 2,  7, 14, 21, 28, 50, 63, 66, 72, 78, 85, 94]),
 array([ 3, 10, 17, 25, 30, 51, 64, 67, 73, 81, 93, 95]))

In [ ]:
type(np.where(diff==1))

tuple

In [ ]:
np.median(step_count[((mood=="Sad") & (calories_burned<np.mean(calories_burned)))])

np.float64(651.0)

In [ ]:
hours_of_sleep[activity=="Active"],calories_burned[activity=="Active"]

(array([5, 6, 8, 5, 6, 4, 5, 8, 4, 5, 6, 5, 6, 7, 6, 7, 6, 5, 6, 7, 8, 8,
        7, 8, 5, 3, 3, 5, 5, 5, 3, 4, 5, 5, 5, 5, 4, 5, 5, 4, 5, 5]),
 array([223, 150, 150,  17, 193,  19, 101, 139, 164, 137,  22,  17,   9,
         17,  32,  35, 220, 116,  23,  44, 131,  86, 194,  60, 121,  93,
         53, 227, 125, 243,  14,  39, 158,   7, 213, 116, 180, 138, 176,
         99,   0,   0]))

In [ ]:
np.round(np.corrcoef(hours_of_sleep[activity=="Active"],calories_burned[activity=="Active"])[0,1],2)

np.float64(0.04)

In [ ]:
sum((step_count<np.median(step_count)) & (hours_of_sleep>np.mean(hours_of_sleep)) & (mood!="Sad"))

np.int64(13)

In [ ]:
f[np.argmax(calories_burned/hours_of_sleep),0]

np.str_('07-11-2017')

In [ ]:
a=calories_burned

In [ ]:
window_size = 3
window_sums = a[:len(a) - window_size + 1] + a[1:len(a) - window_size + 2] + a[2:len(a) - window_size + 3]

# Get max sum and the starting index
max_sum = np.max(window_sums)
start_index = np.argmax(window_sums)

# Extract the 3 elements that form the max sum
max_triplet = a[start_index:start_index + window_size]

print("Max 3-consecutive sum:", max_sum)
print("Triplet:", max_triplet)

Max 3-consecutive sum: 595
Triplet: [227 125 243]


In [ ]:
np.where(a==max_triplet[0]),len(a)

((array([67]),), 96)

In [ ]:
f[67:70,:]

array([['12-12-2017', '7102', 'Neutral', '227', '5', 'Active'],
       ['13-12-2017', '3941', 'Neutral', '125', '5', 'Active'],
       ['14-12-2017', '7422', 'Happy', '243', '5', 'Active']],
      dtype='<U10')

In [2]:
np.pad?

In [3]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [6]:
np.pad(a,(1,)),np.pad(a,(2,))

(array([0, 1, 2, 3, 4, 5, 0]), array([0, 0, 1, 2, 3, 4, 5, 0, 0]))

In [8]:
np.pad(a,(2,3)),np.pad(a,(0,1))

(array([0, 0, 1, 2, 3, 4, 5, 0, 0, 0]), array([1, 2, 3, 4, 5, 0]))

In [9]:
b=np.random.randint(1,99,(2,3))
b

array([[16, 50, 48],
       [28, 67, 11]])

In [17]:
np.pad(b,((1,2),(3,4)),'edge')

array([[16, 16, 16, 16, 50, 48, 48, 48, 48, 48],
       [16, 16, 16, 16, 50, 48, 48, 48, 48, 48],
       [28, 28, 28, 28, 67, 11, 11, 11, 11, 11],
       [28, 28, 28, 28, 67, 11, 11, 11, 11, 11],
       [28, 28, 28, 28, 67, 11, 11, 11, 11, 11]])