In [1]:
import numpy as np
import math

In [ ]:
fact=np.vectorize(math.factorial)

In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,3]])

In [ ]:
fact(a)

array([[    1,     2,     6],
       [   24,   120,   720],
       [ 5040, 40320,     6]])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
n=math.factorial(30)

In [ ]:
type(n)

int

In [ ]:
n

265252859812191058636308480000000

In [ ]:
a=np.random.randint(1,9,(3,2))
b=np.random.randint(1,9,(2,3))
a,b

(array([[6, 6],
        [8, 4],
        [7, 7]]),
 array([[3, 6, 1],
        [8, 8, 8]]))

In [ ]:
np.matmul(a,b)

array([[66, 84, 54],
       [56, 80, 40],
       [77, 98, 63]])

In [ ]:
np.dot(a,b)

array([[66, 84, 54],
       [56, 80, 40],
       [77, 98, 63]])

In [ ]:
a@b

array([[66, 84, 54],
       [56, 80, 40],
       [77, 98, 63]])

In [ ]:
import numpy as np
birds = np.array(['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills'])
age = np.array([5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0])
birds,age

(array(['spoonbills', 'plovers', 'plovers', 'plovers', 'plovers', 'Cranes',
        'plovers', 'plovers', 'Cranes', 'spoonbills'], dtype='<U10'),
 array([5.5, 6. , 3.5, 1.5, 3. , 4. , 3.5, 2. , 5.5, 6. ]))

In [ ]:
x=np.argsort(age)
x

array([3, 7, 4, 2, 6, 5, 0, 8, 1, 9])

In [ ]:
birds[x]

array(['plovers', 'plovers', 'plovers', 'plovers', 'plovers', 'Cranes',
       'spoonbills', 'Cranes', 'plovers', 'spoonbills'], dtype='<U10')

In [ ]:
age

array([5.5, 6. , 3.5, 1.5, 3. , 4. , 3.5, 2. , 5.5, 6. ])

In [ ]:
len(age)

10

In [ ]:
np.split(age,2)

[array([5.5, 6. , 3.5, 1.5, 3. ]), array([4. , 3.5, 2. , 5.5, 6. ])]

In [ ]:
x=np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.split(x,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
np.split(x,4,axis=1)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [ ]:
np.hsplit(x,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
np.vsplit(x,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [ ]:
np.hsplit(x,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [ ]:
np.hsplit(x,(2,3))

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [ ]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.stack((x,x))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
np.vstack((x,x))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hstack((x,x))

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11],
       [12, 13, 14, 15, 12, 13, 14, 15]])

In [ ]:
np.hstack((x,x[:,[0]]))

array([[ 0,  1,  2,  3,  0],
       [ 4,  5,  6,  7,  4],
       [ 8,  9, 10, 11,  8],
       [12, 13, 14, 15, 12]])

In [ ]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hstack((x[:,1:],x[:,[0]]))

array([[ 1,  2,  3,  0],
       [ 5,  6,  7,  4],
       [ 9, 10, 11,  8],
       [13, 14, 15, 12]])

In [ ]:
x,x[:,[0,2]]

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[ 0,  2],
        [ 4,  6],
        [ 8, 10],
        [12, 14]]))

In [ ]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
y=np.where(x==np.max(x))
z=np.where(x>=5,0,1)

In [ ]:
x[y],z

(array([15]),
 array([[1, 1, 1, 1],
        [1, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]))

In [ ]:
y

(array([3]), array([3]))

In [ ]:
y

(array([3]), array([3]))

In [ ]:
y[0][0]

np.int64(3)

In [ ]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
y=np.split(x,(2,3))

In [ ]:
y

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [ ]:
y[-1],y[0:-1]

(array([[12, 13, 14, 15]]),
 [array([[0, 1, 2, 3],
         [4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])])

In [ ]:
np.concatenate((y[-1],*y[0:-1]))

array([[12, 13, 14, 15],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([9,8,7])
np.dot(arr1, arr2)

np.int64(46)

In [ ]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([1,1])
np.dot(arr1, arr2)

array([3, 7])

In [ ]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
x1=np.vstack((x,[0]*x.shape[1]))
x1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [ 0,  0,  0,  0]])

In [ ]:
x1=np.vstack(([0]*x.shape[1],x1))
x1

array([[ 0,  0,  0,  0],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [ 0,  0,  0,  0]])

In [ ]:
x1=np.hstack(([[0]]*x1.shape[0],x1))
x1

array([[ 0,  0,  0,  0,  0],
       [ 0,  0,  1,  2,  3],
       [ 0,  4,  5,  6,  7],
       [ 0,  8,  9, 10, 11],
       [ 0, 12, 13, 14, 15],
       [ 0,  0,  0,  0,  0]])

In [ ]:
x1=np.hstack((x1,[[0]]*x1.shape[0]))
x1

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  2,  3,  0],
       [ 0,  4,  5,  6,  7,  0],
       [ 0,  8,  9, 10, 11,  0],
       [ 0, 12, 13, 14, 15,  0],
       [ 0,  0,  0,  0,  0,  0]])

In [ ]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
s=np.split(x,(2))

In [ ]:
s,s[-1],s[-1:]

([array([[0, 1, 2, 3],
         [4, 5, 6, 7]]),
  array([[ 8,  9, 10, 11],
         [12, 13, 14, 15]])],
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 [array([[ 8,  9, 10, 11],
         [12, 13, 14, 15]])])

In [ ]:
np.concatenate(s[-1:]+s[0:-1])

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

In [ ]:
np.concatenate((s[-1],*s[0:-1]))

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

In [ ]:
np.concatenate((s[-1],*s[0:-1]),axis=1)

array([[ 8,  9, 10, 11,  0,  1,  2,  3],
       [12, 13, 14, 15,  4,  5,  6,  7]])

In [ ]:
np.concatenate(s[-1:]+s[0:-1],axis=1)

array([[ 8,  9, 10, 11,  0,  1,  2,  3],
       [12, 13, 14, 15,  4,  5,  6,  7]])

In [2]:
np.stack?

In [20]:
a=np.random.randint(1,99,(30,))
a,len(a)

(array([68, 50, 49, 95, 76, 63, 77, 19, 41, 51, 37,  7, 52,  2, 81, 67, 62,
        65, 76, 25, 95, 83, 11, 49, 70, 86, 88, 83, 10, 27]),
 30)

In [22]:
np.concatenate(([0],a,[0]))

array([ 0, 68, 50, 49, 95, 76, 63, 77, 19, 41, 51, 37,  7, 52,  2, 81, 67,
       62, 65, 76, 25, 95, 83, 11, 49, 70, 86, 88, 83, 10, 27,  0])

In [17]:
len(np.diff(a,4))

26

In [18]:
np.diff(a)

array([ 43, -19,  56, -71,  71,  -4, -72,  58, -78,  96, -94,  19,  31,
        -3,  -6,  -8, -21,  59, -11, -53,  28, -14,  56,  16, -16,  -7,
       -27,   5, -49])